package com.antaiib.custom.param.v3;


import lombok.Builder;
import lombok.Data;
import org.springframework.web.multipart.MultipartFile;

/**
 * @projectName： A_安泰股份_dev
 * @packageName： com.antaiib.custom.param.v3
 * @ClassName： EasyExcelImportParam
 * @description： EasyExcel 导入参数对象
 * @author： zhangkh
 * @date： 2022/4/1  16:05
 */

@Data
public class EasyExcelImportParam {
    /**
  * 自定义数据表表名
 */
    private String tableName;

    /**
  * 必填字段,多个用逗号隔开
 */
    private String requireField;

    /**
  * 导入文件
 */
    private MultipartFile file;

    /**
  * 读取sheet页数，默认0开始
 */
    @Builder.Default
    private Integer sheetNum=0;

    /**
  * 表头占的行数，从0开始（如果要连表头一起读出来则传0）
 */
    @Builder.Default
    private Integer headRowNum=1;

    /**
  * 一次性批注excel行数
 */
    @Builder.Default
    private Integer batchCommentRowNum=500;

    /**
  * 一次性插入数据库行数
 */
    @Builder.Default
    private Integer batchInsertRowNum=2000;

    /**
  * 导入数据是否验重
 */
    @Builder.Default
    private boolean checkRepeat=true;

    /**
  * 启用临时表验重条数，即导入数据量大于多少时启用临时表验重，仅当checkRepeat 为true 时生效
 */
    @Builder.Default
    private Integer useTempTableNumber=100;

    /**
  * 是否系统自动生成编码，默认false,true时excel填写的值无效
 */
    @Builder.Default
    private boolean autoGeneratedCode=false;

}
