
spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.34.77:8848 #服务注册中心地址
#        namespace: fsn-api-s-simu   #命名空间
#        group: simu #开发的时候，写上自己的组，否则服务调用的时候，会出现调用匹配的错乱
#        register-enabled: false
  application:
    name: custom
  datasource:
    #此处数据源配置不生效，真正生效的数据源配置在lib-custom.jar中
    usePermission: true
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.34.72:3306/fsn_core_custom?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: simu_write
    password: cQpdVLAglMnHf8bJGgeklh/Xs2h+7neQJrkzwpJpOXJ5cjmI/gv/j7L7Nh4nhf2lOuvg2zQAoXofgRa1XgAT3g==
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAI1U848/tBQ/apFKIV2iqbOgg38QM/JmiXMxuiBFCKU3Drw4KtbovYuuJyavvsHdQQ5tDTldy6Z+eklorOAT5l8CAwEAAQ==
##引入dubbo注册中心
#dubbo:
#  application:
#    name: ${spring.application.name}
#    id: ${spring.application.name}
#    qos-enable: false
#    qos-accept-foreign-ip: false
#    metadata-type: local
#  protocol:
#    id: dubbo
#    # dubbo 协议
#    name: dubbo
#    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
#    port: 26600
#    payload: 10485760
#  registry:
#    address: nacos://${spring.cloud.nacos.discovery.server-addr}
#    # 配置namespace命名空间
#    parameters[namespace]: ${spring.cloud.nacos.discovery.namespace}
#    parameters[group]: ${spring.cloud.nacos.discovery.group}
#    use-as-config-center: false
#    check: false
#    register: false
#  consumer:
#    check: false
#    retries: 2
#  cloud:
#    subscribed-services: consumer,log
#
#
##RabbitMQ 配置
##rabbit:
##  enabled: true
##
##ribbon:
##  ReadTimeout: 15000
##  ConnectTimeout: 15000
##  SocketTimeout: 15000
##  MaxAutoRetries: 0
##  MaxAutoRetriesNextServer: 1
#
##Redis 配置
#jedis:
#  address: 192.168.34.72:7000,192.168.34.72:7001,192.168.34.72:7002,192.168.34.74:7000,192.168.34.74:7001,192.168.34.74:7002,192.168.34.75:7000,192.168.34.75:7001,192.168.34.75:7002
#  maxTotal: 100
#  maxIdle: 10
#  maxWaitMillis: 100000
#
#
#sftp:
#  remotePath: /home/s_fusion/s_applications/
#  formFiles: /f1/s_appFiles/forms/
#  host: 192.168.34.73 # 服务器ip
#  port: 22 # ssh端口
#  username: root # 用户名
#  password: h3c.com # 密码
#  # 连接池参数
#  pool:
#    max-total: 10
#    max-idle: 10
#    min-idle: 5
