#配置项目名称
spring:
  application:
    name: mybatis-plus
  #数据库连接
  datasource:
    username: root
    password: Root_12root
    url: jdbc:mysql://127.0.0.1:3306/yz?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
#配置端口
