package com.antaiib.custom.data.entity;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("custom_app_database", "id", CustomAppDatabase.class);
		arp.addMapping("custom_field", "id", CustomField.class);
		arp.addMapping("custom_field_autonumber", "id", CustomFieldAutonumber.class);
		arp.addMapping("custom_field_cascade", "id", CustomFieldCascade.class);
		arp.addMapping("custom_field_show", "id", CustomFieldShow.class);
		arp.addMapping("custom_field_validate", "id", CustomFieldValidate.class);
		arp.addMapping("custom_table", "id", CustomTable.class);
		arp.addMapping("custom_table_classify", "id", CustomTableClassify.class);
		arp.addMapping("custom_table_field_log", "id", CustomTableFieldLog.class);
		arp.addMapping("custom_table_fieldcontrol", "id", CustomTableFieldcontrol.class);
		arp.addMapping("custom_table_sql", "id", CustomTableSql.class);
		arp.addMapping("custom_table_table_rltn", "id", CustomTableTableRltn.class);
		arp.addMapping("custom_form_classify", "id", CustomFormClassify.class);
		arp.addMapping("custom_form_info", "id", CustomFormInfo.class);
		arp.addMapping("custom_form_formula_conf", "id", CustomFormFormulaConf.class);
		arp.addMapping("custom_form_formula_function", "id", CustomFormFormulaFunction.class);
		arp.addMapping("custom_form_formula_operator", "id", CustomFormFormulaOperator.class);
		arp.addMapping("custom_form_formula_variable", "id", CustomFormFormulaVariable.class);
		arp.addMapping("custom_field_comment", "id", CustomFieldComment.class);
		arp.addMapping("custom_scene", "id", CustomScene.class);
		arp.addMapping("custom_table_table_config", "id", CustomTableTableConfig.class);
		arp.addMapping("custom_tree_bind_table_conf", "id", CustomTreeBindTableConf.class);
		arp.addMapping("custom_tree_expand_type", "id", CustomTreeExpandType.class);
		arp.addMapping("custom_table_index", "id", CustomTableIndex.class);
		arp.addMapping("custom_common_phrase", "id", CustomCommonPhrase.class);
		arp.addMapping("custom_form_access_formula_conf", "id", CustomFormAccessFormulaConf.class);
		arp.addMapping("custom_form_related_data_config", "id", CustomFormRelatedDataConfig.class);
		arp.addMapping("custom_person_datatype", "id", CustomPersonDatatype.class);
		arp.addMapping("custom_person_relation_fields", "id", CustomPersonRelationFields.class);
		arp.addMapping("custom_module", "id", CustomModule.class);
		arp.addMapping("custom_module_variable", "id", CustomModuleVariable.class);
		arp.addMapping("custom_module_business_classify", "id", CustomModuleBusinessClassify.class);
		arp.addMapping("custom_sys_table_expand_conf", "id", CustomSysTableExpandConf.class);
	}
}

