package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomModule extends BaseCustomModule<CustomModule> {
	
}
