package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomFormTableRltn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomFormTableRltn extends BaseCustomFormTableRltn<CustomFormTableRltn> {
	
}
