package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomTreeBindTableConf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomTreeBindTableConf extends BaseCustomTreeBindTableConf<CustomTreeBindTableConf> {
	
}
