package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomTableFieldLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomTableFieldLog extends BaseCustomTableFieldLog<CustomTableFieldLog> {
	
}
