package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomTableSql;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomTableSql extends BaseCustomTableSql<CustomTableSql> {
	
}
