package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomTableFieldcontrol;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomTableFieldcontrol extends BaseCustomTableFieldcontrol<CustomTableFieldcontrol> {
	
}
