package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomFormAccessFormulaConf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomFormAccessFormulaConf extends BaseCustomFormAccessFormulaConf<CustomFormAccessFormulaConf> {
	
}
