package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomPersonRelationFields;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomPersonRelationFields extends BaseCustomPersonRelationFields<CustomPersonRelationFields> {
	
}
