package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomFormFormulaFunction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomFormFormulaFunction extends BaseCustomFormFormulaFunction<CustomFormFormulaFunction> {
	
}
