package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomForm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomForm extends BaseCustomForm<CustomForm> {
	
}
