package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomCommonPhrase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomCommonPhrase extends BaseCustomCommonPhrase<CustomCommonPhrase> {
	
}
