package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomSysTableExpandConf;

/**
 * Generated by JFinal.
 *
 * @author yz
 * @since 2022/08/08 11:53
 */
@SuppressWarnings("serial")
public class CustomSysTableExpandConf extends BaseCustomSysTableExpandConf<CustomSysTableExpandConf> {
	
}
