package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomTableClassify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomTableClassify extends BaseCustomTableClassify<CustomTableClassify> {
	
}
