package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomTableTableConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomTableTableConfig extends BaseCustomTableTableConfig<CustomTableTableConfig> {
	
}
