package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomPersonDatatype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomPersonDatatype extends BaseCustomPersonDatatype<CustomPersonDatatype> {
	
}
