package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomFormFormulaVariable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomFormFormulaVariable extends BaseCustomFormFormulaVariable<CustomFormFormulaVariable> {
	
}
