package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomFieldCascade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomFieldCascade extends BaseCustomFieldCascade<CustomFieldCascade> {
	
}
