package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomTableTableRltn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomTableTableRltn extends BaseCustomTableTableRltn<CustomTableTableRltn> {
    private boolean delDateBase;
    public boolean getDelDateBase() {
        return delDateBase;
    }
    public void setDelDateBase(boolean delDateBase) {
        this.delDateBase = delDateBase;
    }
}
