package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomModuleVariable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomModuleVariable extends BaseCustomModuleVariable<CustomModuleVariable> {
	
}
