package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomModuleBusinessClassify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomModuleBusinessClassify extends BaseCustomModuleBusinessClassify<CustomModuleBusinessClassify> {
	
}
