package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomFormFormulaConf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomFormFormulaConf extends BaseCustomFormFormulaConf<CustomFormFormulaConf> {
	
}
