package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomFieldShow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomFieldShow extends BaseCustomFieldShow<CustomFieldShow> {
	
}
