package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomFormFormulaOperator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomFormFormulaOperator extends BaseCustomFormFormulaOperator<CustomFormFormulaOperator> {
	
}
