package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomFormRelatedDataConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomFormRelatedDataConfig extends BaseCustomFormRelatedDataConfig<CustomFormRelatedDataConfig> {
	
}
