package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomFormInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomFormInfo extends BaseCustomFormInfo<CustomFormInfo> {
	
}
