package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomFieldValidate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomFieldValidate extends BaseCustomFieldValidate<CustomFieldValidate> {
	
}
