package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomTreeExpandType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomTreeExpandType extends BaseCustomTreeExpandType<CustomTreeExpandType> {
	
}
