package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomAppDatabase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomAppDatabase extends BaseCustomAppDatabase<CustomAppDatabase> {
	
}
