package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomFormClassify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomFormClassify extends BaseCustomFormClassify<CustomFormClassify> {
	
}
