package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomFieldComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomFieldComment extends BaseCustomFieldComment<CustomFieldComment> {
	
}
