package com.antaiib.custom.data.entity;

import com.antaiib.custom.data.entity.base.BaseCustomFieldAutonumber;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomFieldAutonumber extends BaseCustomFieldAutonumber<CustomFieldAutonumber> {
	
}
