package com.antaiib.custom.data.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomFormClassify<M extends BaseCustomFormClassify<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 应用ID
	 */
	public void setAppId(Long appId) {
		set("app_id", appId);
	}

	/**
	 * 应用ID
	 */
	public Long getAppId() {
		return getLong("app_id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 创建人id
	 */
	public void setCreateId(Long createId) {
		set("create_id", createId);
	}

	/**
	 * 创建人id
	 */
	public Long getCreateId() {
		return getLong("create_id");
	}

	/**
	 * 修改人id
	 */
	public void setUpdateId(Long updateId) {
		set("update_id", updateId);
	}

	/**
	 * 修改人id
	 */
	public Long getUpdateId() {
		return getLong("update_id");
	}

	/**
	 * 来源：1：云，2：端
	 */
	public void setSource(Integer source) {
		set("source", source);
	}

	/**
	 * 来源：1：云，2：端
	 */
	public Integer getSource() {
		return getInt("source");
	}

	/**
	 * 分类名称
	 */
	public void setClassifyName(String classifyName) {
		set("classify_name", classifyName);
	}

	/**
	 * 分类名称
	 */
	public String getClassifyName() {
		return getStr("classify_name");
	}

	/**
	 * 分类编码
	 */
	public void setClassifyCode(String classifyCode) {
		set("classify_code", classifyCode);
	}

	/**
	 * 分类编码
	 */
	public String getClassifyCode() {
		return getStr("classify_code");
	}

	/**
	 * 分类说明
	 */
	public void setClassifyRemark(String classifyRemark) {
		set("classify_remark", classifyRemark);
	}

	/**
	 * 分类说明
	 */
	public String getClassifyRemark() {
		return getStr("classify_remark");
	}

	/**
	 * 父级id
	 */
	public void setParentId(Long parentId) {
		set("parent_id", parentId);
	}

	/**
	 * 父级id
	 */
	public Long getParentId() {
		return getLong("parent_id");
	}

	/**
	 * 所属模块编码
	 */
	public void setModuleCode(String moduleCode){
		set("module_code", moduleCode);
	}

	/**
	 * 所属模块编码
	 */
	public String getModuleCode(){
		return getStr("module_code");
	}

	/**
	 * 业务分类编码
	 */
	public void setBusinessClassifyCode(String businessClassifyCode) {
		set("business_classify_code", businessClassifyCode);
	}

	/**
	 * 业务分类编码
	 */
	public String getBusinessClassifyCode() {
		return getStr("business_classify_code");
	}
}
