package com.antaiib.custom.data.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomFieldComment<M extends BaseCustomFieldComment<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 用户id
	 */
	public void setUserId(Long userId) {
		set("user_id", userId);
	}

	/**
	 * 用户id
	 */
	public Long getUserId() {
		return getLong("user_id");
	}

	/**
	 * 用户名
	 */
	public void setUserName(String userName) {
		set("user_name", userName);
	}

	/**
	 * 用户名
	 */
	public String getUserName() {
		return getStr("user_name");
	}

	/**
	 * 组织
	 */
	public void setUserOrg(String userOrg) {
		set("user_org", userOrg);
	}

	/**
	 * 组织
	 */
	public String getUserOrg() {
		return getStr("user_org");
	}

	/**
	 * appid
	 */
	public void setAppId(Long appId) {
		set("app_id", appId);
	}

	/**
	 * appid
	 */
	public Long getAppId() {
		return getLong("app_id");
	}

	/**
	 * 字段名
	 */
	public void setFieldName(String fieldName) {
		set("field_name", fieldName);
	}

	/**
	 * 字段名
	 */
	public String getFieldName() {
		return getStr("field_name");
	}

	public void setFormId(Long formId) {
		set("form_id", formId);
	}

	public Long getFormId() {
		return getLong("form_id");
	}

	/**
	 * 批示
	 */
	public void setComment(String comment) {
		set("comment", comment);
	}

	/**
	 * 批示
	 */
	public String getComment() {
		return getStr("comment");
	}

	/**
	 * 批示时间
	 */
	public void setCommentTime(java.util.Date commentTime) {
		set("comment_time", commentTime);
	}

	/**
	 * 批示时间
	 */
	public java.util.Date getCommentTime() {
		return get("comment_time");
	}

	/**
	 * 流程实例id
	 */
	public void setProcessInstanceId(String processInstanceId) {
		set("process_instance_id", processInstanceId);
	}

	/**
	 * 流程实例id
	 */
	public String getProcessInstanceId() {
		return getStr("process_instance_id");
	}

	/**
	 * 任务id
	 */
	public void setTaskId(String taskId) {
		set("task_id", taskId);
	}

	/**
	 * 任务id
	 */
	public String getTaskId() {
		return getStr("task_id");
	}

	/**
	 * 附件
	 */
	public void setCommentAttachment(String commentAttachment) {
		set("comment_attachment", commentAttachment);
	}

	/**
	 * 附件
	 */
	public String getCommentAttachment() {
		return getStr("comment_attachment");
	}

	/**
	 * 态度 1-同意 2-不同意 0-已阅
	 */
	public void setCommentAttitude(Integer commentAttitude) {
		set("comment_attitude", commentAttitude);
	}

	/**
	 * 态度 1-同意 2-不同意 0-已阅
	 */
	public Integer getCommentAttitude() {
		return getInt("comment_attitude");
	}

	/**
	 * 签名
	 */
	public void setUserSign(String userSign) {
		set("user_sign", userSign);
	}

	/**
	 * 签名
	 */
	public String getUserSign() {
		return getStr("user_sign");
	}

	/**
	 * 流程节点key
	 */
	public void setTaskDefKey(String taskDefKey) {
		set("task_def_key", taskDefKey);
	}

	/**
	 * 流程节点key
	 */
	public String getTaskDefKey() {
		return getStr("task_def_key");
	}

	/**
	 * 草稿：0否 1是
	 */
	public void setDraft(Integer draft) {
		set("draft", draft);
	}

	/**
	 * 草稿：0否 1是
	 */
	public Integer getDraft() {
		return getInt("draft");
	}

	/**
	 * 批示意见类型 0-办件意见 1-阅件意见
	 */
	public void setCommentType(Integer commentType) {set("comment_type", commentType);}

	/**
	 * 批示意见类型 0-办件意见 1-阅件意见
	 */
	public Integer getCommentType() {
		return getInt("comment_type");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCreateId(Long createId) {
		set("create_id", createId);
	}

	public Long getCreateId() {
		return getLong("create_id");
	}

	public void setUpdateId(Long updateId) {
		set("update_id", updateId);
	}

	public Long getUpdateId() {
		return getLong("update_id");
	}

}
