package com.antaiib.custom.data.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomFieldValidate<M extends BaseCustomFieldValidate<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 表单ID，预留字段
	 */
	public void setFormId(Long formId) {
		set("form_id", formId);
	}

	/**
	 * 表单ID，预留字段
	 */
	public Long getFormId() {
		return getLong("form_id");
	}

	/**
	 * 字段ID
	 */
	public void setFieldId(Long fieldId) {
		set("field_id", fieldId);
	}

	/**
	 * 字段ID
	 */
	public Long getFieldId() {
		return getLong("field_id");
	}

	/**
	 * 字段名称
	 */
	public void setFieldName(String fieldName) {
		set("field_name", fieldName);
	}

	/**
	 * 字段名称
	 */
	public String getFieldName() {
		return getStr("field_name");
	}

	/**
	 * 校验名称
	 */
	public void setValidateName(String validateName) {
		set("validate_name", validateName);
	}

	/**
	 * 校验名称
	 */
	public String getValidateName() {
		return getStr("validate_name");
	}

	/**
	 * 是否必填，0-否，1-是
	 */
	public void setValidateRequire(String validateRequire) {
		set("validate_require", validateRequire);
	}

	/**
	 * 是否必填，0-否，1-是
	 */
	public String getValidateRequire() {
		return getStr("validate_require");
	}

	/**
	 * 校验类型
	 */
	public void setValidateType(String validateType) {
		set("validate_type", validateType);
	}

	/**
	 * 校验类型
	 */
	public String getValidateType() {
		return getStr("validate_type");
	}

	/**
	 * 校验长度
	 */
	public void setValidateLength(Integer validateLength) {
		set("validate_length", validateLength);
	}

	/**
	 * 校验长度
	 */
	public Integer getValidateLength() {
		return getInt("validate_length");
	}

	/**
	 * 自定义校验正则表达式
	 */
	public void setValidateRegex(String validateRegex) {
		set("validate_regex", validateRegex);
	}

	/**
	 * 自定义校验正则表达式
	 */
	public String getValidateRegex() {
		return getStr("validate_regex");
	}

	/**
	 * 当字段类型为整型或者浮点型的时候用于校验最大值
	 */
	public void setValidateMax(String validateMax) {
		set("validate_max", validateMax);
	}

	/**
	 * 当字段类型为整型或者浮点型的时候用于校验最大值
	 */
	public String getValidateMax() {
		return getStr("validate_max");
	}

	/**
	 * 当字段类型为整型或者浮点型的时候用于校验最小值
	 */
	public void setValidateMin(String validateMin) {
		set("validate_min", validateMin);
	}

	/**
	 * 当字段类型为整型或者浮点型的时候用于校验最小值
	 */
	public String getValidateMin() {
		return getStr("validate_min");
	}

	public void setAppId(Long appId) {
		set("app_id", appId);
	}

	public Long getAppId() {
		return getLong("app_id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 创建人id
	 */
	public void setCreateId(Long createId) {
		set("create_id", createId);
	}

	/**
	 * 创建人id
	 */
	public Long getCreateId() {
		return getLong("create_id");
	}

	/**
	 * 修改人id
	 */
	public void setUpdateId(Long updateId) {
		set("update_id", updateId);
	}

	/**
	 * 修改人id
	 */
	public Long getUpdateId() {
		return getLong("update_id");
	}

}
