package com.antaiib.custom.data.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomTableClassify<M extends BaseCustomTableClassify<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 分类名称
	 */
	public void setClassifyName(String classifyName) {
		set("classify_name", classifyName);
	}

	/**
	 * 分类名称
	 */
	public String getClassifyName() {
		return getStr("classify_name");
	}

	/**
	 * 分类编码
	 */
	public void setClassifyCode(String classifyCode) {
		set("classify_code", classifyCode);
	}

	/**
	 * 分类编码
	 */
	public String getClassifyCode() {
		return getStr("classify_code");
	}

	/**
	 * 分类说明
	 */
	public void setClassifyRemark(String classifyRemark) {
		set("classify_remark", classifyRemark);
	}

	/**
	 * 分类说明
	 */
	public String getClassifyRemark() {
		return getStr("classify_remark");
	}

	/**
	 * 父级id
	 */
	public void setParentId(Long parentId) {
		set("parent_id", parentId);
	}

	/**
	 * 父级id
	 */
	public Long getParentId() {
		return getLong("parent_id");
	}

	public void setAppId(Long appId) {
		set("app_id", appId);
	}

	public Long getAppId() {
		return getLong("app_id");
	}

	/**
	 * 等级：1-系统级、2-行业级、3-应用级
	 */
	public void setLevel(Integer level) {
		set("level", level);
	}

	/**
	 * 等级：1-系统级、2-行业级、3-应用级
	 */
	public Integer getLevel() {
		return getInt("level");
	}

	/**
	 * 行业ID
	 */
	public void setIndustryId(Long industryId) {
		set("industry_id", industryId);
	}

	/**
	 * 行业ID
	 */
	public Long getIndustryId() {
		return getLong("industry_id");
	}

	/**
	 * 创建人id
	 */
	public void setCreateId(Long createId) {
		set("create_id", createId);
	}

	/**
	 * 创建人id
	 */
	public Long getCreateId() {
		return getLong("create_id");
	}

	/**
	 * 修改人id
	 */
	public void setUpdateId(Long updateId) {
		set("update_id", updateId);
	}

	/**
	 * 修改人id
	 */
	public Long getUpdateId() {
		return getLong("update_id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
