package com.antaiib.custom.data.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomTableSql<M extends BaseCustomTableSql<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 应用ID
	 */
	public void setAppId(Long appId) {
		set("app_id", appId);
	}

	/**
	 * 应用ID
	 */
	public Long getAppId() {
		return getLong("app_id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 创建人id
	 */
	public void setCreateId(Long createId) {
		set("create_id", createId);
	}

	/**
	 * 创建人id
	 */
	public Long getCreateId() {
		return getLong("create_id");
	}

	/**
	 * 修改人id
	 */
	public void setUpdateId(Long updateId) {
		set("update_id", updateId);
	}

	/**
	 * 修改人id
	 */
	public Long getUpdateId() {
		return getLong("update_id");
	}

	/**
	 * 自定义SQL语句名称
	 */
	public void setSqlName(String sqlName) {
		set("sql_name", sqlName);
	}

	/**
	 * 自定义SQL语句名称
	 */
	public String getSqlName() {
		return getStr("sql_name");
	}

	/**
	 * 自定义SQL语句编码
	 */
	public void setSqlCode(String sqlCode) {
		set("sql_code", sqlCode);
	}

	/**
	 * 自定义SQL语句编码
	 */
	public String getSqlCode() {
		return getStr("sql_code");
	}

	/**
	 * SQL执行类型，insert，update，query，delete
	 */
	public void setSqlAction(String sqlAction) {
		set("sql_action", sqlAction);
	}

	/**
	 * SQL执行类型，insert，update，query，delete
	 */
	public String getSqlAction() {
		return getStr("sql_action");
	}

	/**
	 * 真实SQL，显示SQL处理描述名称后而来
	 */
	public void setSqlReal(String sqlReal) {
		set("sql_real", sqlReal);
	}

	/**
	 * 真实SQL，显示SQL处理描述名称后而来
	 */
	public String getSqlReal() {
		return getStr("sql_real");
	}

	/**
	 * 查询SQL
	 */
	public void setSqlSearch(String sqlSearch) {
		set("sql_search", sqlSearch);
	}

	/**
	 * 查询SQL
	 */
	public String getSqlSearch() {
		return getStr("sql_search");
	}

}
