package com.antaiib.custom.data.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomField<M extends BaseCustomField<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 创建人id
	 */
	public void setCreateId(Long createId) {
		set("create_id", createId);
	}

	/**
	 * 创建人id
	 */
	public Long getCreateId() {
		return getLong("create_id");
	}

	/**
	 * 修改人id
	 */
	public void setUpdateId(Long updateId) {
		set("update_id", updateId);
	}

	/**
	 * 修改人id
	 */
	public Long getUpdateId() {
		return getLong("update_id");
	}

	public void setAppId(Long appId) {
		set("app_id", appId);
	}

	public Long getAppId() {
		return getLong("app_id");
	}

	/**
	 * 字段编码
	 */
	public void setFieldCode(String fieldCode) {
		set("field_code", fieldCode);
	}

	/**
	 * 字段编码
	 */
	public String getFieldCode() {
		return getStr("field_code");
	}

	/**
	 * 字段描述名称
	 */
	public void setFieldDesname(String fieldDesname) {
		set("field_desname", fieldDesname);
	}

	/**
	 * 字段描述名称
	 */
	public String getFieldDesname() {
		return getStr("field_desname");
	}

	/**
	 * 字段实际名称
	 */
	public void setFieldName(String fieldName) {
		set("field_name", fieldName);
	}

	/**
	 * 字段实际名称
	 */
	public String getFieldName() {
		return getStr("field_name");
	}

	/**
	 * 所属数据表
	 */
	public void setTableId(Long tableId) {
		set("table_id", tableId);
	}

	/**
	 * 所属数据表
	 */
	public Long getTableId() {
		return getLong("table_id");
	}

	/**
	 * 字段类型（1-整型，2-浮点型，3-字符型，4-文本型）
	 */
	public void setFieldType(String fieldType) {
		set("field_type", fieldType);
	}

	/**
	 * 字段类型（1-整型，2-浮点型，3-字符型，4-文本型）
	 */
	public String getFieldType() {
		return getStr("field_type");
	}

	/**
	 * 字段长度
	 */
	public void setFieldLen(String fieldLen) {
		set("field_len", fieldLen);
	}

	/**
	 * 字段长度
	 */
	public String getFieldLen() {
		return getStr("field_len");
	}

	/**
	 * 小数位数，只有当字段类型为浮点型的时候有值，其他类型默认值为0
	 */
	public void setFieldDecimals(String fieldDecimals) {
		set("field_decimals", fieldDecimals);
	}

	/**
	 * 小数位数，只有当字段类型为浮点型的时候有值，其他类型默认值为0
	 */
	public String getFieldDecimals() {
		return getStr("field_decimals");
	}

	/**
	 * 字段说明
	 */
	public void setFieldDes(String fieldDes) {
		set("field_des", fieldDes);
	}

	/**
	 * 字段说明
	 */
	public String getFieldDes() {
		return getStr("field_des");
	}

	/**
	 * 显示方式
	 */
	public void setFieldShow(String fieldShow) {
		set("field_show", fieldShow);
	}

	/**
	 * 显示方式
	 */
	public String getFieldShow() {
		return getStr("field_show");
	}

	/**
	 * 取值范围
	 */
	public void setFieldValue(String fieldValue) {
		set("field_value", fieldValue);
	}

	/**
	 * 取值范围
	 */
	public String getFieldValue() {
		return getStr("field_value");
	}

	/**
	 * 字段标识，0系统字段 1编码字段，2预设字段，3普通字段
	 */
	public void setFieldFlag(Integer fieldFlag) {
		set("field_flag", fieldFlag);
	}

	/**
	 * 字段标识，0系统字段 1编码字段，2预设字段，3普通字段
	 */
	public Integer getFieldFlag() {
		return getInt("field_flag");
	}

	/**
	 * 应用域名
	 */
	public void setAppDomain(String appDomain) {
		set("app_domain", appDomain);
	}

	/**
	 * 应用域名
	 */
	public String getAppDomain() {
		return getStr("app_domain");
	}

	/**
	 * 所属数据表名称
	 */
	public void setTableName(String tableName) {
		set("table_name", tableName);
	}

	/**
	 * 所属数据表名称
	 */
	public String getTableName() {
		return getStr("table_name");
	}

	/**
	 * 默认值
	 */
	public void setDefaultFieldvalue(String defaultFieldvalue) {
		set("default_fieldvalue", defaultFieldvalue);
	}

	/**
	 * 默认值
	 */
	public String getDefaultFieldvalue() {
		return getStr("default_fieldvalue");
	}

	/**
	 * 自定义sql编码
	 */
	public void setCustomSqlCode(String customSqlCode) {
		set("custom_sql_code", customSqlCode);
	}

	/**
	 * 自定义sql编码
	 */
	public String getCustomSqlCode() {
		return getStr("custom_sql_code");
	}

	/**
	 * 额外属性
	 */
	public void setAttributeInfo(String attributeInfo) {
		set("attribute_info", attributeInfo);
	}

	/**
	 * 额外属性
	 */
	public String getAttributeInfo() {
		return getStr("attribute_info");
	}

	/**
	 * 自定义属性，json格式存储
	 */
	public void setCustomAttributeInfo(String customAttributeInfo) {
		set("custom_attribute_info", customAttributeInfo);
	}

	/**
	 * 自定义属性，json格式存储
	 */
	public String getCustomAttributeInfo() {
		return getStr("custom_attribute_info");
	}

	/**
	 * 字段排序码
	 */
	public void setFieldSort(Integer fieldSort) {
		set("field_sort", fieldSort);
	}

	/**
	 * 字段排序码
	 */
	public Integer getFieldSort() {
		return getInt("field_sort");
	}

	/**
	 * 校验类型，手机号：CELLPHONE_TYPE，固话：PHONE_TYPE，手机号和固话：TEL_TYPE，身份证：IDENTIFICATION_TYPE，链接：URL_TYPE，车牌号：CARNUMBER_TYPE，QQ：QQ_TYPE，邮箱：EMAIL_TYPE
	 */
	public void setValidateType(String validateType) {
		set("validate_type", validateType);
	}

	/**
	 * 校验类型，手机号：CELLPHONE_TYPE，固话：PHONE_TYPE，手机号和固话：TEL_TYPE，身份证：IDENTIFICATION_TYPE，链接：URL_TYPE，车牌号：CARNUMBER_TYPE，QQ：QQ_TYPE，邮箱：EMAIL_TYPE
	 */
	public String getValidateType() {
		return getStr("validate_type");
	}

	public void setSource(Integer source) {
		set("source", source);
	}

	public Integer getSource() {
		return getInt("source");
	}

	/**
	 * 数据库字段默认值
	 */
	public void setFieldDefaultValue(String fieldDefaultValue) {
		set("field_default_value", fieldDefaultValue);
	}

	/**
	 * 数据库字段默认值
	 */
	public String getFieldDefaultValue() {
		return getStr("field_default_value");
	}

	/**
	 * 字段值不能为空 0：否，可以为空 1：是，不能为空
	 */
	public void setFieldNotNull(Integer fieldNotNull) {
		set("field_not_null", fieldNotNull);
	}
	
	/**
	 * 字段值不能为空 0：否，可以为空 1：是，不能为空
	 */
	public Integer getFieldNotNull() {
		return getInt("field_not_null");
	}

	/**
	 * 是否可删除。0-可删除，1-不可删除
	 */
	public void setDeletable(Integer deletable) {
		set("deletable", deletable);
	}
	
	/**
	 * 是否可删除。0-可删除，1-不可删除
	 */
	public Integer getDeletable() {
		return getInt("deletable");
	}

	/**
	 * 字典管理
	 */
	public void setDictCode(Long dictCode) {
		set("dict_code", dictCode);
	}

	/**
	 * 字典管理
	 */
	public Long getDictCode() {
		return getLong("dict_code");
	}

	/**
	 * 表单使用该字段 0-隐藏 1-默认 2-必填
	 * @param fieldFormShow
	 */
	public void setFieldFormShow(Integer fieldFormShow) {
		set("field_form_show",fieldFormShow);
	}

	/**
	 * 表单使用该字段 0-隐藏 1-默认 2-必填
	 */
	public Integer getFieldFormShow() {
		return getInt("field_form_show");
	}
}
