package com.antaiib.custom.data.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomTreeBindTableConf<M extends BaseCustomTreeBindTableConf<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 创建人
	 */
	public void setCreateId(Long createId) {
		set("create_id", createId);
	}

	/**
	 * 创建人
	 */
	public Long getCreateId() {
		return getLong("create_id");
	}

	/**
	 * 修改人
	 */
	public void setUpdateId(Long updateId) {
		set("update_id", updateId);
	}

	/**
	 * 修改人
	 */
	public Long getUpdateId() {
		return getLong("update_id");
	}

	/**
	 * 应用 id
	 */
	public void setAppId(Long appId) {
		set("app_id", appId);
	}

	/**
	 * 应用 id
	 */
	public Long getAppId() {
		return getLong("app_id");
	}

	/**
	 * 来源 : 1 :云，2 :端
	 */
	public void setSource(Integer source) {
		set("source", source);
	}

	/**
	 * 来源 : 1 :云，2 :端
	 */
	public Integer getSource() {
		return getInt("source");
	}

	/**
	 * 场景编码
	 */
	public void setSceneCode(String sceneCode) {
		set("scene_code", sceneCode);
	}

	/**
	 * 场景编码
	 */
	public String getSceneCode() {
		return getStr("scene_code");
	}

	/**
	 * 主表类型，0-树表，1-数据表
	 */
	public void setTableType(Integer tableType) {
		set("table_type", tableType);
	}

	/**
	 * 主表类型，0-树表，1-数据表
	 */
	public Integer getTableType() {
		return getInt("table_type");
	}

	/**
	 * 关联表类型 1-拓展 2-拓展从表
	 */
	public void setRltnTableType(Integer rltnTableType) {
		set("rltn_table_type", rltnTableType);
	}

	/**
	 * 关联表类型 1-拓展 2-拓展从表
	 */
	public Integer getRltnTableType() {
		return getInt("rltn_table_type");
	}

	/**
	 * 关联编码
	 */
	public void setRltnCode(String rltnCode) {
		set("rltn_code", rltnCode);
	}

	/**
	 * 关联编码
	 */
	public String getRltnCode() {
		return getStr("rltn_code");
	}

	/**
	 * 绑定的表名
	 */
	public void setBindTableName(String bindTableName) {
		set("bind_table_name", bindTableName);
	}

	/**
	 * 绑定的表名
	 */
	public String getBindTableName() {
		return getStr("bind_table_name");
	}

	/**
	 * 绑定的字段名，多个以，隔开
	 */
	public void setBindFields(String bindFields) {
		set("bind_fields", bindFields);
	}

	/**
	 * 绑定的字段名，多个以，隔开
	 */
	public String getBindFields() {
		return getStr("bind_fields");
	}

	/**
	 * 扩展类别关联编码
	 */
	public void setTypeRltnCode(String typeRltnCode) {
		set("type_rltn_code", typeRltnCode);
	}

	/**
	 * 扩展类别关联编码
	 */
	public String getTypeRltnCode() {
		return getStr("type_rltn_code");
	}

	/**
	 * 字段配置
	 */
	public void setFieldConfig(String fieldConfig) {
		set("field_config", fieldConfig);
	}

	/**
	 * 字段配置
	 */
	public String getFieldConfig() {
		return getStr("field_config");
	}

}
