package com.antaiib.custom.data.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomTableTableConfig<M extends BaseCustomTableTableConfig<M>> extends Model<M> implements IBean {

	/**
	 * id使用主键策略
	 */
	public void setId(Long id) {
		set("id", id);
	}

	/**
	 * id使用主键策略
	 */
	public Long getId() {
		return getLong("id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 创建人
	 */
	public void setCreateId(Long createId) {
		set("create_id", createId);
	}

	/**
	 * 创建人
	 */
	public Long getCreateId() {
		return getLong("create_id");
	}

	/**
	 * 修改人
	 */
	public void setUpdateId(Long updateId) {
		set("update_id", updateId);
	}

	/**
	 * 修改人
	 */
	public Long getUpdateId() {
		return getLong("update_id");
	}

	/**
	 * 应用id
	 */
	public void setAppId(Long appId) {
		set("app_id", appId);
	}

	/**
	 * 应用id
	 */
	public Long getAppId() {
		return getLong("app_id");
	}

	/**
	 * 来源：1：云，2：端
	 */
	public void setSource(Integer source) {
		set("source", source);
	}

	/**
	 * 来源：1：云，2：端
	 */
	public Integer getSource() {
		return getInt("source");
	}

	/**
	 * 场景编码
	 */
	public void setSceneCode(String sceneCode) {
		set("scene_code", sceneCode);
	}

	/**
	 * 场景编码
	 */
	public String getSceneCode() {
		return getStr("scene_code");
	}

	/**
	 * 表名
	 */
	public void setTableName(String tableName) {
		set("table_name", tableName);
	}

	/**
	 * 表名
	 */
	public String getTableName() {
		return getStr("table_name");
	}

	/**
	 * 0-树表 1-基础表
	 */
	public void setTableType(Integer tableType) {
		set("table_type", tableType);
	}

	/**
	 * 0-树表 1-基础表
	 */
	public Integer getTableType() {
		return getInt("table_type");
	}

	/**
	 * 树表层级或类型 基础表类型值
	 */
	public void setLevelTypeValue(String levelTypeValue) {
		set("level_type_value", levelTypeValue);
	}

	/**
	 * 树表层级或类型 基础表类型值
	 */
	public String getLevelTypeValue() {
		return getStr("level_type_value");
	}

	/**
	 * 树表层级或类型 基础表类型名称
	 */
	public void setLevelTypeName(String levelTypeName) {
		set("level_type_name", levelTypeName);
	}

	/**
	 * 树表层级或类型 基础表类型名称
	 */
	public String getLevelTypeName() {
		return getStr("level_type_name");
	}

	/**
	 * 树层级关联基础类型值
	 */
	public void setLevelRltnBasicValue(String levelRltnBasicValue) {
		set("level_rltn_basic_value", levelRltnBasicValue);
	}

	/**
	 * 树层级关联基础类型值
	 */
	public String getLevelRltnBasicValue() {
		return getStr("level_rltn_basic_value");
	}

	/**
	 * 拓展表关联编码
	 */
	public void setExpandCode(String expandCode) {
		set("expand_code", expandCode);
	}

	/**
	 * 拓展表关联编码
	 */
	public String getExpandCode() {
		return getStr("expand_code");
	}

	/**
	 * 拓展从表关联编码
	 */
	public void setExpandSubCode(String expandSubCode) {
		set("expand_sub_code", expandSubCode);
	}

	/**
	 * 拓展从表关联编码
	 */
	public String getExpandSubCode() {
		return getStr("expand_sub_code");
	}

}
