package com.antaiib.custom.data.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomFieldCascade<M extends BaseCustomFieldCascade<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 创建人id
	 */
	public void setCreateId(Long createId) {
		set("create_id", createId);
	}

	/**
	 * 创建人id
	 */
	public Long getCreateId() {
		return getLong("create_id");
	}

	/**
	 * 修改人id
	 */
	public void setUpdateId(Long updateId) {
		set("update_id", updateId);
	}

	/**
	 * 修改人id
	 */
	public Long getUpdateId() {
		return getLong("update_id");
	}

	/**
	 * 应用ID
	 */
	public void setAppId(Long appId) {
		set("app_id", appId);
	}

	/**
	 * 应用ID
	 */
	public Long getAppId() {
		return getLong("app_id");
	}

	/**
	 * 级联名称
	 */
	public void setName(String name) {
		set("name", name);
	}

	/**
	 * 级联名称
	 */
	public String getName() {
		return getStr("name");
	}

	/**
	 * 字段所属数据表名称
	 */
	public void setTableName(String tableName) {
		set("table_name", tableName);
	}

	/**
	 * 字段所属数据表名称
	 */
	public String getTableName() {
		return getStr("table_name");
	}

	/**
	 * 触发字段
	 */
	public void setTriggerField(String triggerField) {
		set("trigger_field", triggerField);
	}

	/**
	 * 触发字段
	 */
	public String getTriggerField() {
		return getStr("trigger_field");
	}

	/**
	 * 级联字段
	 */
	public void setCascadeField(String cascadeField) {
		set("cascade_field", cascadeField);
	}

	/**
	 * 级联字段
	 */
	public String getCascadeField() {
		return getStr("cascade_field");
	}

	/**
	 * 自定义SQL语句编码
	 */
	public void setCustomSqlCode(String customSqlCode) {
		set("custom_sql_code", customSqlCode);
	}

	/**
	 * 自定义SQL语句编码
	 */
	public String getCustomSqlCode() {
		return getStr("custom_sql_code");
	}

}
