package com.antaiib.custom.data.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomTreeExpandType<M extends BaseCustomTreeExpandType<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setCreateId(Long createId) {
		set("create_id", createId);
	}

	public Long getCreateId() {
		return getLong("create_id");
	}

	public void setUpdateId(Long updateId) {
		set("update_id", updateId);
	}

	public Long getUpdateId() {
		return getLong("update_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setSource(Integer source) {
		set("source", source);
	}

	public Integer getSource() {
		return getInt("source");
	}

	public void setAppId(Long appId) {
		set("app_id", appId);
	}

	public Long getAppId() {
		return getLong("app_id");
	}

	/**
	 * 枚举值，config_type是1时为类别值，是2时为层级
	 */
	public void setEnumValue(String enumValue) {
		set("enum_value", enumValue);
	}

	/**
	 * 枚举值，config_type是1时为类别值，是2时为层级
	 */
	public String getEnumValue() {
		return getStr("enum_value");
	}

	/**
	 * 树层级关联基础类型值
	 */
	public void setEnumRltnValue(String enumRltnValue) {
		set("enum_rltn_value", enumRltnValue);
	}

	/**
	 * 树层级关联基础类型值
	 */
	public String getEnumRltnValue() {
		return getStr("enum_rltn_value");
	}

	/**
	 * 自定义类别编码
	 */
	public void setTypeCode(String typeCode) {
		set("type_code", typeCode);
	}

	/**
	 * 自定义类别编码
	 */
	public String getTypeCode() {
		return getStr("type_code");
	}

	/**
	 * 自定义类别名称
	 */
	public void setTypeName(String typeName) {
		set("type_name", typeName);
	}

	/**
	 * 自定义类别名称
	 */
	public String getTypeName() {
		return getStr("type_name");
	}

	/**
	 * 主表类型，0-树表，1-数据表
	 */
	public void setTableType(Integer tableType) {
		set("table_type", tableType);
	}

	/**
	 * 主表类型，0-树表，1-数据表
	 */
	public Integer getTableType() {
		return getInt("table_type");
	}

	/**
	 * 状态 0-删除 1-正常
	 */
	public void setStatus(Integer status) {
		set("status", status);
	}

	/**
	 * 状态 0-删除 1-正常
	 */
	public Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 场景编码
	 */
	public void setSceneCode(String sceneCode) {
		set("scene_code", sceneCode);
	}

	/**
	 * 场景编码
	 */
	public String getSceneCode() {
		return getStr("scene_code");
	}

	/**
	 * 类别描述
	 */
	public void setTypeDescription(String typeDescription) {
		set("type_description", typeDescription);
	}

	/**
	 * 类别描述
	 */
	public String getTypeDescription() {
		return getStr("type_description");
	}

}
