package com.antaiib.custom.data.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomTableTableRltn<M extends BaseCustomTableTableRltn<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 创建人id
	 */
	public void setCreateId(Long createId) {
		set("create_id", createId);
	}

	/**
	 * 创建人id
	 */
	public Long getCreateId() {
		return getLong("create_id");
	}

	/**
	 * 修改人id
	 */
	public void setUpdateId(Long updateId) {
		set("update_id", updateId);
	}

	/**
	 * 修改人id
	 */
	public Long getUpdateId() {
		return getLong("update_id");
	}

	/**
	 * 应用ID
	 */
	public void setAppId(Long appId) {
		set("app_id", appId);
	}

	/**
	 * 应用ID
	 */
	public Long getAppId() {
		return getLong("app_id");
	}

	/**
	 * 关联名称
	 */
	public void setRltnName(String rltnName) {
		set("rltn_name", rltnName);
	}

	/**
	 * 关联名称
	 */
	public String getRltnName() {
		return getStr("rltn_name");
	}

	/**
	 * 关联编码
	 */
	public void setRltnCode(String rltnCode) {
		set("rltn_code", rltnCode);
	}

	/**
	 * 关联编码
	 */
	public String getRltnCode() {
		return getStr("rltn_code");
	}

	/**
	 * 关联类型，1:一对一，2:一对多，3:多对多
	 */
	public void setRltnType(String rltnType) {
		set("rltn_type", rltnType);
	}

	/**
	 * 关联类型，1:一对一，2:一对多，3:多对多
	 */
	public String getRltnType() {
		return getStr("rltn_type");
	}

	/**
	 * 多对多关联表存放域名
	 */
	public void setRltnTableAppDomain(String rltnTableAppDomain) {
		set("rltn_table_app_domain", rltnTableAppDomain);
	}

	/**
	 * 多对多关联表存放域名
	 */
	public String getRltnTableAppDomain() {
		return getStr("rltn_table_app_domain");
	}

	/**
	 * 主键表ID
	 */
	public void setPrimaryTableId(Long primaryTableId) {
		set("primary_table_id", primaryTableId);
	}

	/**
	 * 主键表ID
	 */
	public Long getPrimaryTableId() {
		return getLong("primary_table_id");
	}

	/**
	 * 主键表名称
	 */
	public void setPrimaryTableName(String primaryTableName) {
		set("primary_table_name", primaryTableName);
	}

	/**
	 * 主键表名称
	 */
	public String getPrimaryTableName() {
		return getStr("primary_table_name");
	}

	/**
	 * 主键表关联字段ID
	 */
	public void setPrimaryFieldId(Long primaryFieldId) {
		set("primary_field_id", primaryFieldId);
	}

	/**
	 * 主键表关联字段ID
	 */
	public Long getPrimaryFieldId() {
		return getLong("primary_field_id");
	}

	/**
	 * 主键表关联字段名称
	 */
	public void setPrimaryFieldName(String primaryFieldName) {
		set("primary_field_name", primaryFieldName);
	}

	/**
	 * 主键表关联字段名称
	 */
	public String getPrimaryFieldName() {
		return getStr("primary_field_name");
	}

	/**
	 * 外键表ID
	 */
	public void setForeignTableId(Long foreignTableId) {
		set("foreign_table_id", foreignTableId);
	}

	/**
	 * 外键表ID
	 */
	public Long getForeignTableId() {
		return getLong("foreign_table_id");
	}

	/**
	 * 外键表名称
	 */
	public void setForeignTableName(String foreignTableName) {
		set("foreign_table_name", foreignTableName);
	}

	/**
	 * 外键表名称
	 */
	public String getForeignTableName() {
		return getStr("foreign_table_name");
	}

	/**
	 * 外键表关联字段ID
	 */
	public void setForeignFieldId(Long foreignFieldId) {
		set("foreign_field_id", foreignFieldId);
	}

	/**
	 * 外键表关联字段ID
	 */
	public Long getForeignFieldId() {
		return getLong("foreign_field_id");
	}

	/**
	 * 外键表关联字段名称
	 */
	public void setForeignFieldName(String foreignFieldName) {
		set("foreign_field_name", foreignFieldName);
	}

	/**
	 * 外键表关联字段名称
	 */
	public String getForeignFieldName() {
		return getStr("foreign_field_name");
	}

	/**
	 * 多对多关联时生成的关联数据表
	 */
	public void setRltnTableName(String rltnTableName) {
		set("rltn_table_name", rltnTableName);
	}

	/**
	 * 多对多关联时生成的关联数据表
	 */
	public String getRltnTableName() {
		return getStr("rltn_table_name");
	}

	/**
	 * 是否级联删除。0-否，1-是
	 */
	public void setCascadeDeleteFlag(Integer cascadeDeleteFlag) {
		set("cascade_delete_flag", cascadeDeleteFlag);
	}

	/**
	 * 是否级联删除。0-否，1-是
	 */
	public Integer getCascadeDeleteFlag() {
		return getInt("cascade_delete_flag");
	}

	/**
	 * 从表有数据是否删除主表 0-否 1-是
	 */
	public void setForeignDataDeleteFlag(Integer foreignDataDeleteFlag) {
		set("foreign_data_delete_flag", foreignDataDeleteFlag);
	}
	
	/**
	 * 从表有数据是否删除主表 0-否 1-是
	 */
	public Integer getForeignDataDeleteFlag() {
		return getInt("foreign_data_delete_flag");
	}

	/**
	 * 从表查询是否关联主表数据 0-否 ， 1-是

	 */
	public void setQueryPrimaryData(Integer queryPrimaryData) {
		set("query_primary_data", queryPrimaryData);
	}
	
	/**
	 * 从表查询是否关联主表数据 0-否 ， 1-是

	 */
	public Integer getQueryPrimaryData() {
		return getInt("query_primary_data");
	}

	/**
	 * 来源：1：云，2：端
	 */
	public void setSource(Integer source) {
		set("source", source);
	}

	/**
	 * 来源：1：云，2：端
	 */
	public Integer getSource() {
		return getInt("source");
	}

	/**
	 * 主键表应用域名
	 */
	public void setPrimaryTableAppDomain(String primaryTableAppDomain) {
		set("primary_table_app_domain", primaryTableAppDomain);
	}
	
	/**
	 * 主键表应用域名
	 */
	public String getPrimaryTableAppDomain() {
		return getStr("primary_table_app_domain");
	}

	/**
	 * 外键表应用域名
	 */
	public void setForeignTableAppDomain(String foreignTableAppDomain) {
		set("foreign_table_app_domain", foreignTableAppDomain);
	}
	
	/**
	 * 外键表应用域名
	 */
	public String getForeignTableAppDomain() {
		return getStr("foreign_table_app_domain");
	}

	/**
	 * 级别类型（0-同级别关联，1-系统级和应用级关联）
	 */
	public void setLevelType(Integer levelType) {
		set("level_type", levelType);
	}
	
	/**
	 * 级别类型（0-同级别关联，1-系统级和应用级关联）
	 */
	public Integer getLevelType() {
		return getInt("level_type");
	}

}
