package com.antaiib.custom.data.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomAppDatabase<M extends BaseCustomAppDatabase<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	/**
	 * 应用名称
	 */
	public void setAppName(String appName) {
		set("app_name", appName);
	}
	
	/**
	 * 应用名称
	 */
	public String getAppName() {
		return getStr("app_name");
	}

	/**
	 * 应用域名
	 */
	public void setAppDomain(String appDomain) {
		set("app_domain", appDomain);
	}
	
	/**
	 * 应用域名
	 */
	public String getAppDomain() {
		return getStr("app_domain");
	}

	public void setAppId(Long appId) {
		set("app_id", appId);
	}
	
	public Long getAppId() {
		return getLong("app_id");
	}

	/**
	 * 类型
	 */
	public void setDatabaseType(String databaseType) {
		set("database_type", databaseType);
	}
	
	/**
	 * 类型
	 */
	public String getDatabaseType() {
		return getStr("database_type");
	}

	/**
	 * 驱动类名
	 */
	public void setDatabaseDriverclassname(String databaseDriverclassname) {
		set("database_driverClassName", databaseDriverclassname);
	}
	
	/**
	 * 驱动类名
	 */
	public String getDatabaseDriverclassname() {
		return getStr("database_driverClassName");
	}

	/**
	 * 地址链接
	 */
	public void setDatabaseUrl(String databaseUrl) {
		set("database_url", databaseUrl);
	}
	
	/**
	 * 地址链接
	 */
	public String getDatabaseUrl() {
		return getStr("database_url");
	}

	/**
	 * 用户名
	 */
	public void setDatabaseUsername(String databaseUsername) {
		set("database_username", databaseUsername);
	}
	
	/**
	 * 用户名
	 */
	public String getDatabaseUsername() {
		return getStr("database_username");
	}

	/**
	 * 密码
	 */
	public void setDatabasePassword(String databasePassword) {
		set("database_password", databasePassword);
	}
	
	/**
	 * 密码
	 */
	public String getDatabasePassword() {
		return getStr("database_password");
	}

	/**
	 * 0:不开启;1:开启。默认不开启。
	 */
	public void setDatabaseUsepermission(Integer databaseUsepermission) {
		set("database_usePermission", databaseUsepermission);
	}
	
	/**
	 * 0:不开启;1:开启。默认不开启。
	 */
	public Integer getDatabaseUsepermission() {
		return getInt("database_usePermission");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 创建人id
	 */
	public void setCreateId(Long createId) {
		set("create_id", createId);
	}
	
	/**
	 * 创建人id
	 */
	public Long getCreateId() {
		return getLong("create_id");
	}

	/**
	 * 修改人id
	 */
	public void setUpdateId(Long updateId) {
		set("update_id", updateId);
	}
	
	/**
	 * 修改人id
	 */
	public Long getUpdateId() {
		return getLong("update_id");
	}

	/**
	 * 启用状态 0：未启用，1：启用
	 */
	public void setStatus(Integer status) {
		set("status", status);
	}
	
	/**
	 * 启用状态 0：未启用，1：启用
	 */
	public Integer getStatus() {
		return getInt("status");
	}

}
