package com.antaiib.custom.data.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomTableFieldLog<M extends BaseCustomTableFieldLog<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 创建人id
	 */
	public void setCreateId(Long createId) {
		set("create_id", createId);
	}

	/**
	 * 创建人id
	 */
	public Long getCreateId() {
		return getLong("create_id");
	}

	/**
	 * 修改人id
	 */
	public void setUpdateId(Long updateId) {
		set("update_id", updateId);
	}

	/**
	 * 修改人id
	 */
	public Long getUpdateId() {
		return getLong("update_id");
	}

	/**
	 * 应用ID
	 */
	public void setAppId(Long appId) {
		set("app_id", appId);
	}

	/**
	 * 应用ID
	 */
	public Long getAppId() {
		return getLong("app_id");
	}

	/**
	 * 操作类型：create：新建，modify：修改，drop：删除
	 */
	public void setOperateType(String operateType) {
		set("operate_type", operateType);
	}

	/**
	 * 操作类型：create：新建，modify：修改，drop：删除，update：更新
	 */
	public String getOperateType() {
		return getStr("operate_type");
	}

	/**
	 * 数据表或字段执行的sql语句
	 */
	public void setSqlLog(String sqlLog) {
		set("sql_log", sqlLog);
	}

	/**
	 * 数据表或字段执行的sql语句
	 */
	public String getSqlLog() {
		return getStr("sql_log");
	}

	/**
	 * 达梦数据库数据表或字段执行的sql语句
	 */
	public void setDamengSqlLog(String damengSqlLog) {
		set("dameng_sql_log", damengSqlLog);
	}

	/**
	 * 达梦数据库数据表或字段执行的sql语句
	 */
	public String getDamengSqlLog() {
		return getStr("dameng_sql_log");
	}
	/**
	 * 表名
	 */
	public void setTableName(String tableName){
		set("table_name", tableName);
	}
	/**
	 * 表名
	 */
	public String getTableName(){
		return getStr("table_name");
	}
	/**
	 * 数据库名
	 */
	public void setDatabaseName(String databaseName){
		set("database_name", databaseName);
	}
	/**
	 * 数据库名
	 */
	public String getDatabaseName(){
		return getStr("database_name");
	}

	/**
	 * 存放关联sql
	 */
	public void setRelationSqlLog(String relationSqlLog) {
		set("relation_sql_log", relationSqlLog);
	}

	/**
	 * 存放关联sql
	 */
	public String getRelationSqlLog() {
		return getStr("relation_sql_log");
	}

	/**
	 * 存放sql的数据源名称
	 */
	public void setConfigName(String configName) {
		set("config_name", configName);
	}

	/**
	 * 存放sql的数据源名称
	 */
	public String getConfigName() {
		return getStr("config_name");
	}
}
