package com.antaiib.custom.data.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomFormInfo<M extends BaseCustomFormInfo<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 应用ID
	 */
	public void setAppId(Long appId) {
		set("app_id", appId);
	}

	/**
	 * 应用ID
	 */
	public Long getAppId() {
		return getLong("app_id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 创建人id
	 */
	public void setCreateId(Long createId) {
		set("create_id", createId);
	}

	/**
	 * 创建人id
	 */
	public Long getCreateId() {
		return getLong("create_id");
	}

	/**
	 * 修改人id
	 */
	public void setUpdateId(Long updateId) {
		set("update_id", updateId);
	}

	/**
	 * 修改人id
	 */
	public Long getUpdateId() {
		return getLong("update_id");
	}

	/**
	 * 来源：1：云，2：端
	 */
	public void setSource(Integer source) {
		set("source", source);
	}

	/**
	 * 来源：1：云，2：端
	 */
	public Integer getSource() {
		return getInt("source");
	}

	/**
	 * 表单名称
	 */
	public void setFormName(String formName) {
		set("form_name", formName);
	}

	/**
	 * 表单名称
	 */
	public String getFormName() {
		return getStr("form_name");
	}

	/**
	 * 表单编码
	 */
	public void setFormCode(String formCode) {
		set("form_code", formCode);
	}

	/**
	 * 表单编码
	 */
	public String getFormCode() {
		return getStr("form_code");
	}

	/**
	 * 表单内容
	 */
	public void setPageContent(String pageContent) {
		set("page_content", pageContent);
	}

	/**
	 * 表单内容
	 */
	public String getPageContent() {
		return getStr("page_content");
	}

	/**
	 * 页面组件code
	 */
	public void setPageComponentsCode(String pageComponentsCode) {
		set("page_components_code", pageComponentsCode);
	}

	/**
	 * 页面组件code
	 */
	public String getPageComponentsCode() {
		return getStr("page_components_code");
	}

	/**
	 * 分辨率-高
	 */
	public void setPageResolutionHeight(String pageResolutionHeight) {
		set("page_resolution_height", pageResolutionHeight);
	}

	/**
	 * 分辨率-高
	 */
	public String getPageResolutionHeight() {
		return getStr("page_resolution_height");
	}

	/**
	 * 分辨率-宽
	 */
	public void setPageResolutionWidth(String pageResolutionWidth) {
		set("page_resolution_width", pageResolutionWidth);
	}

	/**
	 * 分辨率-宽
	 */
	public String getPageResolutionWidth() {
		return getStr("page_resolution_width");
	}

	/**
	 * 页面布局，1-自由式布局，2-响应式布局
	 */
	public void setPageLayout(Integer pageLayout) {
		set("page_layout", pageLayout);
	}

	/**
	 * 页面布局，1-自由式布局，2-响应式布局
	 */
	public Integer getPageLayout() {
		return getInt("page_layout");
	}

	/**
	 * 页面属性
	 */
	public void setPageAttrs(String pageAttrs) {
		set("page_attrs", pageAttrs);
	}

	/**
	 * 页面属性
	 */
	public String getPageAttrs() {
		return getStr("page_attrs");
	}

	/**
	 * 表单分类id
	 */
	public void setClassifyId(Long classifyId) {
		set("classify_id", classifyId);
	}

	/**
	 * 表单分类id
	 */
	public Long getClassifyId() {
		return getLong("classify_id");
	}

	/**
	 * 使用范围
	 */
	public void setUseScope(String useScope) {
		set("use_scope", useScope);
	}

	/**
	 * 使用范围
	 */
	public String getUseScope() {
		return getStr("use_scope");
	}

	/**
	 * 表单状态。0-启用，1-停用，2-删除
	 */
	public void setFormStatus(String formStatus) {
		set("form_status", formStatus);
	}

	/**
	 * 表单状态。0-启用，1-停用，2-删除
	 */
	public String getFormStatus() {
		return getStr("form_status");
	}

	/**
	 * 使用的主表名称
	 */
	public void setUsePrimaryTableName(String usePrimaryTableName) {
		set("use_primary_table_name", usePrimaryTableName);
	}

	/**
	 * 使用的主表名称
	 */
	public String getUsePrimaryTableName() {
		return getStr("use_primary_table_name");
	}

	/**
	 * 使用的主表字段名称，JSON对象文本格式
	 */
	public void setUsePrimaryFieldName(String usePrimaryFieldName) {
		set("use_primary_field_name", usePrimaryFieldName);
	}

	/**
	 * 使用的主表字段名称，JSON对象文本格式
	 */
	public String getUsePrimaryFieldName() {
		return getStr("use_primary_field_name");
	}

	/**
	 * 使用的子表名称，多个以,隔开
	 */
	public void setUseSubTableName(String useSubTableName) {
		set("use_sub_table_name", useSubTableName);
	}

	/**
	 * 使用的子表名称，多个以,隔开
	 */
	public String getUseSubTableName() {
		return getStr("use_sub_table_name");
	}

	/**
	 * 使用的子表字段名称，JSON对象文本格式
	 */
	public void setUseSubFieldName(String useSubFieldName) {
		set("use_sub_field_name", useSubFieldName);
	}

	/**
	 * 使用的子表字段名称，JSON对象文本格式
	 */
	public String getUseSubFieldName() {
		return getStr("use_sub_field_name");
	}

	/**
	 * 表单类型，1-流程表单，2-业务表单
	 */
	public void setFormType(String formType) {
		set("form_type", formType);
	}
	
	/**
	 * 表单类型，1-流程表单，2-业务表单
	 */
	public String getFormType() {
		return getStr("form_type");
	}

	/**
	 * 所属模块编码
	 */
	public void setModuleCode(String moduleCode){
		set("module_code", moduleCode);
	}

	/**
	 * 所属模块编码
	 */
	public String getModuleCode(){
		return getStr("module_code");
	}

	/**
	 * 业务分类编码
	 */
	public void setBusinessClassifyCode(String businessClassifyCode) {
		set("business_classify_code", businessClassifyCode);
	}

	/**
	 * 业务分类编码
	 */
	public String getBusinessClassifyCode() {
		return getStr("business_classify_code");
	}

	public void setFormFlag(Integer formFlag) {
		set("form_flag",formFlag);
	}

	public Integer getFormFlag() {
		return  getInt("form_flag");
	}

	public  void setDfsInfo(String dfsInfo) {
		set("dfs_info",dfsInfo);

	}

	public String getDfsInfo() {
		return getStr("dfs_info");
	}

}
