package com.antaiib.custom.data.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomTableFieldcontrol<M extends BaseCustomTableFieldcontrol<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 创建人id
	 */
	public void setCreateId(Long createId) {
		set("create_id", createId);
	}

	/**
	 * 创建人id
	 */
	public Long getCreateId() {
		return getLong("create_id");
	}

	/**
	 * 修改人id
	 */
	public void setUpdateId(Long updateId) {
		set("update_id", updateId);
	}

	/**
	 * 修改人id
	 */
	public Long getUpdateId() {
		return getLong("update_id");
	}

	public void setAppId(Long appId) {
		set("app_id", appId);
	}

	public Long getAppId() {
		return getLong("app_id");
	}

	/**
	 * 模块ID（暂时未用到，后期会用到）
	 */
	public void setModuleId(Long moduleId) {
		set("module_id", moduleId);
	}

	/**
	 * 模块ID（暂时未用到，后期会用到）
	 */
	public Long getModuleId() {
		return getLong("module_id");
	}

	/**
	 * 0:列表显示，1:查询字段，2:链接字段，3:导出字段，4:表单可读，5:表单可写，6:表单隐藏，7:列表编辑，8:全局变量
	 */
	public void setFieldcontrolType(Boolean fieldcontrolType) {
		set("fieldcontrol_type", fieldcontrolType);
	}

	/**
	 * 0:列表显示，1:查询字段，2:链接字段，3:导出字段，4:表单可读，5:表单可写，6:表单隐藏，7:列表编辑，8:全局变量
	 */
	public Boolean getFieldcontrolType() {
		return get("fieldcontrol_type");
	}

	/**
	 * 字段ID
	 */
	public void setFieldId(Long fieldId) {
		set("field_id", fieldId);
	}

	/**
	 * 字段ID
	 */
	public Long getFieldId() {
		return getLong("field_id");
	}

	/**
	 * 字段名称
	 */
	public void setFieldName(String fieldName) {
		set("field_name", fieldName);
	}

	/**
	 * 字段名称
	 */
	public String getFieldName() {
		return getStr("field_name");
	}

	/**
	 * 数据表名
	 */
	public void setTableName(String tableName) {
		set("table_name", tableName);
	}

	/**
	 * 数据表名
	 */
	public String getTableName() {
		return getStr("table_name");
	}

}
