package com.antaiib.custom.data.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomSysTableExpandConf<M extends BaseCustomSysTableExpandConf<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 创建人id
	 */
	public void setCreateId(Long createId) {
		set("create_id", createId);
	}
	
	/**
	 * 创建人id
	 */
	public Long getCreateId() {
		return getLong("create_id");
	}

	/**
	 * 修改人id
	 */
	public void setUpdateId(Long updateId) {
		set("update_id", updateId);
	}
	
	/**
	 * 修改人id
	 */
	public Long getUpdateId() {
		return getLong("update_id");
	}

	/**
	 * 所属信息
	 */
	public void setBelongInfo(String belongInfo) {
		set("belong_info", belongInfo);
	}
	
	/**
	 * 所属信息
	 */
	public String getBelongInfo() {
		return getStr("belong_info");
	}

	/**
	 * 应用ID
	 */
	public void setAppId(Long appId) {
		set("app_id", appId);
	}
	
	/**
	 * 应用ID
	 */
	public Long getAppId() {
		return getLong("app_id");
	}

	/**
	 * 来源：1：云，2：端
	 */
	public void setSource(Integer source) {
		set("source", source);
	}
	
	/**
	 * 来源：1：云，2：端
	 */
	public Integer getSource() {
		return getInt("source");
	}

	/**
	 * 表名
	 */
	public void setTableName(String tableName) {
		set("table_name", tableName);
	}
	
	/**
	 * 表名
	 */
	public String getTableName() {
		return getStr("table_name");
	}

	/**
	 * 表描述，供展示使用，如：会议管理模块-会议申请表
	 */
	public void setTableDesc(String tableDesc) {
		set("table_desc", tableDesc);
	}
	
	/**
	 * 表描述，供展示使用，如：会议管理模块-会议申请表
	 */
	public String getTableDesc() {
		return getStr("table_desc");
	}

	/**
	 * 应用域名
	 */
	public void setAppDomain(String appDomain) {
		set("app_domain", appDomain);
	}
	
	/**
	 * 应用域名
	 */
	public String getAppDomain() {
		return getStr("app_domain");
	}

	/**
	 * 可关联的类型，多个以逗号隔开。0-一对一，1-一对多
	 */
	public void setRltnType(String rltnType) {
		set("rltn_type", rltnType);
	}
	
	/**
	 * 可关联的类型，多个以逗号隔开。0-一对一，1-一对多
	 */
	public String getRltnType() {
		return getStr("rltn_type");
	}

	/**
	 * 可关联字段，多个以逗号隔开。
	 */
	public void setRltnFieldName(String rltnFieldName) {
		set("rltn_field_name", rltnFieldName);
	}
	
	/**
	 * 可关联字段，多个以逗号隔开。
	 */
	public String getRltnFieldName() {
		return getStr("rltn_field_name");
	}

	/**
	 * 开放扩展的应用id，多个以逗号隔开，为空时所有应用可用
	 */
	public void setEnableAppId(String enableAppId) {
		set("enable_app_id", enableAppId);
	}
	
	/**
	 * 开放扩展的应用id，多个以逗号隔开，为空时所有应用可用
	 */
	public String getEnableAppId() {
		return getStr("enable_app_id");
	}

	/**
	 * 是否启用标志位，0-禁用，1-启用
	 */
	public void setEnableFlag(Integer enableFlag) {
		set("enable_flag", enableFlag);
	}
	
	/**
	 * 是否启用标志位，0-禁用，1-启用
	 */
	public Integer getEnableFlag() {
		return getInt("enable_flag");
	}

}
